### ISSUE TITLE
使用 python3和2都回出现这个错误

### ISSUE THREAD

**Issue by mobailabs** [hauntek/python-ngrok#10]
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "python-ngrok.py", line 283, in HKClient
    newsock = connectlocal(loacladdr['lhost'], loacladdr['lport'])
KeyError: 'lhost'

```

**Comment by hauntek** [comment]
你设置渠道配置问题

**Comment by mobailabs** [comment]
谢谢哈,能指点下大概是哪里配置,是客户端配置还是服务器配置呢?
我用编译的 mac 客户端就可以正常.

**Comment by hauntek** [comment]
ngrok.cofing

**Comment by mobailabs** [comment]
好吧.我发现不能使用随机域名,必须要自定义域名.
