### ISSUE TITLE
我在老毛子上跑有问题

### ISSUE THREAD

**Issue by oit63** [hauntek/python-ngrok#18]
[RT-AC1200HP /etc/storage/ngr]# ./test
[2018/10/02 16:14:29] [INFO] [client] python-ngrok v1.5
[2018/10/02 16:14:29] [DEBUG] [Conn:3] New connection to: [我的服务器ip地址]:4443
Traceback (most recent call last)
  File "/etc/storage/ngr/python-ngrok-master/python-ngrok.py", line 344, in <module>
    thread.start()
  File "/opt/lib/python2.7/threading.py", line 736, in start
thread.error: can't start new thread

在ddwrt上也出现过，当时用 ulimit -s 512 就可以跑了，
但是hiboy的老毛子不知道为什么还是不行，
想问下从python这边看有没有什么解决方法呢？

**Comment by oit63** [comment]
用了php版的在它上面暂时用吧。可能是老毛子内核限制

**Comment by hauntek** [comment]
可能是你老毛子固件python线程模块有问题，或者你python版本太低。

**Comment by oit63** [comment]
应该还是固件的问题. 因为都是entware安装的.之前在pandorabox 可以跑, 换了老毛子就跑不动了.
